### ISSUE TITLE
How can I force to update my self?

### ISSUE THREAD

**Issue by lipis** [k0kubun/githubranks#1]

**Comment by k0kubun** [comment]
Thank you for reporting an issue! Sorry for the delay. I didn't watch this repo.

There is no way to force to update your data now. But I'm planning to solve the problem.
Recently I have some time to develop this app, the feature will be shipped :soon:.

**Comment by lipis** [comment]
![](http://i1.kym-cdn.com/photos/images/facebook/000/159/325/1262055260350.jpg)

**Comment by k0kubun** [comment]
I implemented a button to update yourself. Could you check it?
From the button, you can request an update to the background queue. It takes about 5 seconds to update your data.

![](http://i.gyazo.com/6034e453ef565a96fd8822b7c16e6787.gif)

**Comment by lipis** [comment]
Not really sure if it worked.. (as after 5 minutes) at least the top 2 of my projects are still couple of stars behind and my profile page is constantly being reloaded every 4-5 seconds..

**Comment by k0kubun** [comment]
Oh, I'm so sorry. Now I'm deploying an application and running mysql ddl on the server. And mysql version is 5.5. So it causes table lock.
I could confirm that your job was queued. Please wait.

**Comment by k0kubun** [comment]
I cancelled the deployment because it may take a long time.

Your job failed because of the table lock. I'm sorry again.
I restarted the mysqld to solve the table lock, and I queued your data update manually. It succeeded. I think it will succeed next time.

**Comment by lipis** [comment]
No worries.. and ou don't have to be sorry or anything.. it happens and I'm happy to help :)

**Comment by lipis** [comment]
worked smoothly now :) thanks

**Comment by k0kubun** [comment]
I'm glad to hear that! Thank you for testing :)
